# Generated by Django 5.2.7 on 2025-11-02 19:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/resumes')),
                ('extracted_text', models.TextField(null=True)),
                ('token_size', models.BigIntegerField(null=True)),
                ('status', models.CharField(choices=[('0', 'Uploaded'), ('1', 'Processing'), ('2', 'Done'), ('5', 'Failed')], db_default='0', max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='parsed_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=355, null=True)),
                ('emails', models.JSONField(default=dict, null=True)),
                ('phones', models.JSONField(default=dict, null=True)),
                ('skills', models.JSONField(default=dict, null=True)),
                ('education', models.JSONField(default=dict, null=True)),
                ('experience_years', models.FloatField(null=True)),
                ('summary_text', models.TextField(null=True)),
                ('keywords', models.JSONField(default=dict, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resume_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='resumes.resume')),
            ],
        ),
    ]
