# Generated by Django 5.2.7 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_alter_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='parsed_data',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
