# Generated by Django 5.2.7 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_parsed_data_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('0', 'Uploaded'), ('1', 'Processing'), ('2', 'Done'), ('5', 'Failed'), ('7', 'Deleted')], db_default='0', max_length=1),
        ),
    ]
