# Generated by Django 5.2.7 on 2025-11-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skills', models.JSONField(default=list)),
                ('source', models.CharField(choices=[('indeed', 'Indeed'), ('linkedin', 'LinkedIn')], max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('apply_url', models.URLField(blank=True, null=True)),
                ('remote', models.BooleanField(default=False)),
                ('salary', models.CharField(blank=True, max_length=255, null=True)),
                ('date_posted', models.DateField(blank=True, null=True)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('title', 'company', 'source_url', 'date_posted')},
            },
        ),
    ]
