# Generated by Django 5.2.7 on 2025-11-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='j_id',
            field=models.CharField(null=True, unique=True),
        ),
    ]
