# Generated by Django 5.2.7 on 2025-11-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_joblisting_j_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='j_id',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source',
            field=models.TextField(null=True),
        ),
    ]
