# Generated by Django 5.2.7 on 2025-11-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_joblisting_j_id_alter_joblisting_source'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='joblisting',
            unique_together=set(),
        ),
    ]
