# Generated by Django 5.2.7 on 2025-11-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_joblisting_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='apply_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
