# Generated by Django 5.2.7 on 2025-11-07 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_joblisting_apply_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('5', 'Deleted')], default='1', max_length=1),
        ),
    ]
