# Generated by Django 5.2.7 on 2025-11-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_joblisting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='joblisting',
            name='experience_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
