# Generated by Django 5.2.7 on 2025-11-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_savedjobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Active'), ('5', 'Deleted')], db_default='1', max_length=1),
        ),
    ]
