# Generated by Django 5.2.7 on 2025-11-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='experience_years',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
