# Generated by Django 5.2.7 on 2025-11-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_accounts_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='is_admin',
            field=models.BooleanField(db_default=False),
        ),
    ]
